!!python/object:argparse.Namespace
save_dir: exp/NCNet3
SR_rate: 4
pretrained_model: ''
epochs: 300
batch_size: 64
augment: false
workers: 0
device: 0
div_factor: 50
final_div_factor: 0.5
lr_max: 0.0025
pct_epoch: 50
